name: portal_proposta_comercial
description: Portal de Cadastro de Clientes e Propostas Comerciais
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  intl: ^0.19.0
  google_fonts: ^6.2.1
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
